spring:
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    ## Data.sql insert
    defer-datasource-initialization: true
  datasource:
    jdbc-url: jdbc:h2:tcp://localhost:9095/mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
