server:
  port: 5050

spring:
  # H2-Console
  h2:
    console:
      enabled: true
  application:
    name: kopring-basic-app
  jpa:
    # Show Console SQL Query
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        # format SQL Logger
        format_sql: true
        # Hibernate Statistics Logger
        generate_statistics: true

logging:
  level:
    org:
      hibernate:
        # Statistics Logger
        stat: debug
        # Parameter Trace
        type: trace
