server:
  port: 5050

spring:
  # H2-Console
  h2:
    console:
      enabled: true
  application:
    name: weasley
  jpa:
    # Show Console SQL Query
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        # ORM ID value
        id:
          new_generator_mappings: false
        # format SQL Logger
        format_sql: true
        # Hibernate Statistics Logger
        generate_statistics: true
    generate-ddl: true
    open-in-view: true

logging:
  level:
    org:
      hibernate:
        # Statistics Logger
        stat: debug
        # Parameter Trace
        type: trace

google:
  jwkUrl: https://www.googleapis.com/oauth2/v3/certs
