# DataBase Connection
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ENC(+HIwCzptNpf8+PETTnc8v7GQbr8QObp/fXf8C+5ZtfTepvAjNRts1wvnYRz0+WggP0Y+SU0v0ZeUuz2UEg4mAaxi5ohyovPI8L1bxIHh1T3JmTyLHeR2cg==)
    username: ENC(p0ZzSlK9oCJlQVCxvhVFhw==)
    password: ENC(wlvmrK26o4pdEh+vOKdwxA==)
    driver-class-name: com.mysql.cj.jdbc.Driver

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
